pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from version control system (e.g. Git)
                git branch: 'main', url: 'https://github.com/ShafiudeenKameel/CC-ecommerce.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build Docker image
                
                dir('user-microservice'){
                    
                    bat 'docker build -t user-microservice:4 .'
                }
                
            }
        }
        // stage('Run Tests') {
        //     steps {
        //         // Run tests for the microservice
        //         sh 'docker run your-user-microservice npm test'
        //     }
        // }
//         stage('Push Docker Image') {
//             steps {
//                 // Push Docker image to a container registry (e.g. Docker Hub)
//                 sh 'docker push user-microservice'
//             }
//         }
        stage('Deploy to Kubernetes') {
            steps {
                dir('user-microservice'){
                    // Deploy the microservice to Kubernetes using kubectl
                    bat 'kubectl apply -f user-microservice-deployment.yaml'
                    bat 'kubectl apply -f user-microservice-service-service.yaml'
                } 
            }
        }
    }
}
