apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice-kb
          image: user-microservice:4
          ports:
            - containerPort: 7070
          env:
            - name: MONGODB_HOST
              value: mongodb  # Use the hostname of the mongodb service
            - name: MONGODB_PORT
              value: "27017"  # Use the port of the mongodb service
